# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f1a8072ca8b9252cf8da5d785e8cd32aa35922349ec98764697352ab8b8c64079fa2099e21e0e5b523bf3d16083654c617cc51e52917c59a8e0e940f1de9945

test:
  secret_key_base: be135b77d7055bec3f864b4f0003be8a18f23b9d45025279898a1bd1b5044d6300fe44e8f0340aed2ad797b0da7313b6769bd19dc89e458d44f5b8f28a84360f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
